//------------------------------------------------------------------------------
// <auto-generated>
//     Ten kod został wygenerowany przez narzędzie.
//     Wersja wykonawcza:4.0.30319.42000
//
//     Zmiany w tym pliku mogą spowodować nieprawidłowe zachowanie i zostaną utracone, jeśli
//     kod zostanie ponownie wygenerowany.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Zad1.Properties {
    using System;
    
    
    /// <summary>
    ///   Klasa zasobu wymagająca zdefiniowania typu do wyszukiwania zlokalizowanych ciągów itd.
    /// </summary>
    // Ta klasa została automatycznie wygenerowana za pomocą klasy StronglyTypedResourceBuilder
    // przez narzędzie, takie jak ResGen lub Visual Studio.
    // Aby dodać lub usunąć składową, edytuj plik ResX, a następnie ponownie uruchom narzędzie ResGen
    // z opcją /str lub ponownie utwórz projekt VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        /// Zwraca buforowane wystąpienie ResourceManager używane przez tę klasę.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Zad1.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Przesłania właściwość CurrentUICulture bieżącego wątku dla wszystkich
        ///   przypadków przeszukiwania zasobów za pomocą tej klasy zasobów wymagającej zdefiniowania typu.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu [{&quot;ID&quot;:36872,&quot;Numer&quot;:&quot;REZ/F/000038/20&quot;,&quot;Data&quot;:&quot;2020-11-30T00:00:00&quot;,&quot;Kontrahent&quot;:{&quot;ID&quot;:6570,&quot;Nazwa&quot;:&quot;Ing. Fouad Chihada - ŠADI BILAL&quot;,&quot;NIP&quot;:&quot;SK1081224628&quot;},&quot;Pozycje&quot;:[{&quot;ID&quot;:80452,&quot;Nazwa&quot;:&quot;Drukarka WIFI&quot;,&quot;Ilosc&quot;:1.0,&quot;Towar&quot;:{&quot;se&quot;:null,&quot;ID&quot;:176,&quot;Nazwa&quot;:&quot;Drukarka WIFI&quot;,&quot;EAN&quot;:&quot;&quot;,&quot;Typ&quot;:0},&quot;Jednostka&quot;:&quot;szt&quot;,&quot;Cena&quot;:35.0}]},{&quot;ID&quot;:36873,&quot;Numer&quot;:&quot;REZ/F/000039/20&quot;,&quot;Data&quot;:&quot;2020-11-30T00:00:00&quot;,&quot;Kontrahent&quot;:{&quot;ID&quot;:6565,&quot;Nazwa&quot;:&quot;BUSINESS 4 JOY, s. r. o.&quot;,&quot;NIP&quot;:&quot;SK 2023228988&quot;},&quot;Pozycje&quot;:[{&quot;ID&quot;:80453,&quot;Nazwa&quot;:&quot;Drukarka blue [obcięto pozostałą część ciągu]&quot;;.
        /// </summary>
        public static string dane {
            get {
                return ResourceManager.GetString("dane", resourceCulture);
            }
        }
    }
}
