//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Zad1.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Zad1.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [{&quot;ID&quot;:36872,&quot;Numer&quot;:&quot;&quot;,&quot;Data&quot;:&quot;2020-11-30T00:00:00&quot;,&quot;Kontrahent&quot;:{&quot;ID&quot;:6570,&quot;Nazwa&quot;:&quot;Ing. Fouad Chihada - ŠADI BILAL&quot;,&quot;NIP&quot;:&quot;SK1081224628&quot;},&quot;Pozycje&quot;:[{&quot;ID&quot;:80452,&quot;Nazwa&quot;:&quot;Drukarka WIFI&quot;,&quot;Ilosc&quot;:1.0,&quot;Towar&quot;:{&quot;se&quot;:null,&quot;ID&quot;:176,&quot;Nazwa&quot;:&quot;Drukarka WIFI&quot;,&quot;EAN&quot;:&quot;&quot;,&quot;Typ&quot;:0},&quot;Jednostka&quot;:&quot;szt&quot;,&quot;Cena&quot;:35.0}]},{&quot;ID&quot;:36873,&quot;Numer&quot;:&quot;&quot;,&quot;Data&quot;:&quot;2020-11-30T00:00:00&quot;,&quot;Kontrahent&quot;:{&quot;ID&quot;:6565,&quot;Nazwa&quot;:&quot;BUSINESS 4 JOY, s. r. o.&quot;,&quot;NIP&quot;:&quot;SK 2023228988&quot;},&quot;Pozycje&quot;:[{&quot;ID&quot;:80453,&quot;Nazwa&quot;:&quot;Drukarka bluetooth (ROS)&quot;,&quot;Ilosc&quot;:1.0,&quot;Towa [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string dane {
            get {
                return ResourceManager.GetString("dane", resourceCulture);
            }
        }
    }
}
